appointment/urls.py
from django.urls import path
from appointment.views import (
    appointment_status_view,
    appointment_list_view,
    make_appointment_view,
    appointment_edit_view,
    appointment_change_status_view,
    appointment_delete_view,
)

app_name = 'appointment'

urlpatterns = [
    path('customer/status', appointment_status_view, name = "status"),
    path('staff/list', appointment_list_view, name = "list"),
    path('customer/make-appointment', make_appointment_view, name = "add"),
    path('customer/edit-appointment/<int:id>', appointment_edit_view, name = "edit"),
    path('staff/delete-appointment/<int:id>', appointment_delete_view, name = "delete"),
    path('change-status/<int:id>/<str:status>', appointment_change_status_view, name = "change-status"),
]

laboratoryapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home.views import home_screen_view
from account.views import (
    login_view,
    logout_view,
    registration_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name="home"),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('register/', registration_view, name="register"),
    path('appointment/', include('appointment.urls', 'appointment')),
    path('service/', include('services.urls', 'services')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

services/urls.py
from django.urls import path
from services.views import service_add_view, service_list_view, service_edit_view, service_delete_view

app_name = 'services'

urlpatterns = [
    path('list', service_list_view, name = 'list' ),
    path('add', service_add_view, name = 'add' ),
    path('edit/<int:id>', service_edit_view, name = "edit"),
    path('delete/<int:id>', service_delete_view, name = "delete"),
]

appointment/models.py
from django.db import models
from django.conf import settings
from services.models import Services

STATUS_CHOICES = [
    ('WA', 'Waiting Approval'),
    ('A', 'Approved'),
    ('R', 'Rejected'),
    ('C', 'Canceled'),
    ('F', 'Finished')
]

# Create your models here.
class Appointment(models.Model):
    registration_id = models.PositiveIntegerField(unique=True)
    customer        = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    service         = models.ForeignKey(Services, on_delete=models.CASCADE)
    date            = models.DateField(verbose_name='date')
    status          = models.CharField(max_length=2, choices=STATUS_CHOICES, default='WA')

    def __str__(self):
        return str(self.registration_id)
    
    class Meta:
        ordering=["registration_id"]

appointment/forms.py
from django import forms
from appointment.models import Appointment
from services.models import Services

class MakeAppointmentForm(forms.ModelForm):
    
    
    class Meta :
        model = Appointment
        fields = ['service', 'date']

    # def clean(self):
    #     print(self.cleaned_data)
    #     service = Services.objects.get(service=self.cleaned_data.get('service'))
    #     self.cleaned_data['service'] = service
    #     return         super(MakeAppointmentForm, self)

appointment/views.py
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404
from appointment.models import Appointment
from services.models import Services
from appointment.forms import MakeAppointmentForm
from django.http import HttpResponseForbidden

# Create your views here.
def appointment_status_view(request):
    context = {}

    user = request.user
    try :
        appointments = Appointment.objects.filter(customer_id = user.pk)
        context['appointments'] = appointments
        return render(request, 'appointment/appointment_status.html', context)
    except Appointment.DoesNotExist:
        return render(request, 'appointment/appointment_status.html')

def appointment_list_view(request):
    context = {}

    try :
        appointments = Appointment.objects.all()
        context['appointments'] = appointments
        return render(request, 'appointment/appointment_list.html', context)
    except Appointment.DoesNotExist:
        return render(request, 'appointment/appointment_list.html')


def make_appointment_view(request):
    context = {}

    user = request.user

    if request.POST :
        form = MakeAppointmentForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.customer = user
            obj.registration_id = get_new_registration_id()
            print(get_new_registration_id())
            obj.save()
            form = MakeAppointmentForm()
    else :
        form = MakeAppointmentForm()

    services = Services.objects.all()

    context['services'] = services
    context['form'] = form
    context['is_edit'] = False

    return render(request, 'appointment/make_appointment.html', context)

def get_new_registration_id():
    appointment = Appointment.objects.last()

    return appointment.registration_id + 1


def appointment_change_status_view(request, id, status):

    user = request.user
    if not user.is_authenticated:
        return HttpResponseForbidden()

    appointment = get_object_or_404(Appointment, registration_id=id)

    appointment.status = status
    appointment.save()

    if user.is_staff:
        return redirect('appointment:list')
    else:
        return redirect('appointment:status')

def appointment_edit_view(request, id):
    context = {}

    user = request.user

    if not user.is_authenticated:
        return HttpResponseForbidden()

    appointment = get_object_or_404(Appointment, registration_id=id)

    if request.POST :
        form = MakeAppointmentForm(request.POST, instance=appointment)
        if form.is_valid():
            form.save()
            return redirect('appointment:list')
    else :
        form = MakeAppointmentForm()

    services = Services.objects.all()

    context['services'] = services
    context['appointment'] = appointment
    context['form'] = form
    context['is_edit'] = True

    return render(request, 'appointment/edit_appointment.html', context)

def appointment_delete_view(request, id):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return HttpResponseForbidden()

    appointment = get_object_or_404(Appointment, registration_id=id)

    appointment.delete()

    return redirect('appointment:list')

appointment/templates/appointment/appointment_list.html
{% extends 'dashboard.html'%}

{% block dashboard_content %}
<section id="appointment-list">
    <h3>Appointment List</h3>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Registration ID</th>
          <th scope="col">Customer</th>
          <th scope="col">Service</th>
          <th scope="col">Date</th>
          <th scope="col">Status</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for appointment in appointments %}
        <tr>
          <td scope="row">{{appointment.registration_id}}</td>
          <td scope="row">{{appointment.customer}}</td>
          <td scope="row">{{appointment.service}}</td>
          <td scope="row">{{appointment.date}}</td>
          {% if appointment.status == "WA" %}
          <td scope="row" style="color: black;">Waiting Approval</td>
          {% elif appointment.status == "A" %}
          <td scope="row" style="color: green;">Approved</td>
          {% elif appointment.status == "C" %}
          <td scope="row" style="color: red;">Canceled</td>
          {% elif appointment.status == "R" %}
          <td scope="row" style="color: red;">Rejected</td>
          {% else %}
          <td scope="row" style="color: gray;">Finished</td>
          {% endif %}
          <td scope="row">
            <span><a href="{% url 'appointment:change-status' id=appointment.registration_id status='A' %}" class="btn btn-success btn-sm">Approve</a></span>
            <span><a href="{% url 'appointment:change-status' id=appointment.registration_id status='R' %}" class="btn btn-warning btn-sm">Reject</a></span>
            <span><a href="{% url 'appointment:delete' appointment.registration_id %}" class="btn btn-danger btn-sm">Remove</a></span>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </section> 
{% endblock dashboard_content %}

appointment/templates/appointment/appointment_status.html
{% extends 'dashboard.html'%}

{% block dashboard_content %}
<section id="appointment-list">
    <h3>Appointment Status</h3>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Registration ID</th>
          <th scope="col">Service</th>
          <th scope="col">Date</th>
          <th scope="col">Status</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for appointment in appointments %}
        <tr>
          <td scope="row">{{appointment.registration_id}}</td>
          <td scope="row">{{appointment.service}}</td>
          <td scope="row">{{appointment.date}}</td>
          {% if appointment.status == "WA" %}
          <td scope="row" style="color: black;">Waiting Approval</td>
          {% elif appointment.status == "A" %}
          <td scope="row" style="color: green;">Approved</td>
          {% elif appointment.status == "C" %}
          <td scope="row" style="color: red;">Canceled</td>
          {% elif appointment.status == "R" %}
          <td scope="row" style="color: red;">Rejected</td>
          {% else %}
          <td scope="row" style="color: gray;">Finished</td>
          {% endif %}
          <td scope="row">
            <a href="{% url 'appointment:edit' appointment.registration_id %}" class="btn btn-primary btn-sm">Edit</a>
            <a href="{% url 'appointment:change-status' id=appointment.registration_id status='C' %}" class="btn btn-danger btn-sm">Cancel</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </section> 
{% endblock dashboard_content %}

appointment/templates/appointment/edit_appointment.html
{% extends 'dashboard.html'%}

{% block dashboard_content %}

<section id="edit-appointment">
    <h3>Edit Appointment</h3>
    <form method="post"> {% csrf_token %}
      <div class="form-group">
        <label for="service">Select service</label>
        <select name="service" class="form-control">
          {% for service in services %}
            {% if service.service is appointment.service %}
            <option value="{{service.pk}}" selected>{{service.service}}</option>
            {% else %}
            <option value="{{service.pk}}">{{service.service}}</option>
            {% endif %}
          {% endfor %}
        </select>
      </div>
      <div class="form-group">
        <label for="date">Date</label>
        <input name="date" value="{{appoinment.date}}"" type="date" class="form-control">
      </div>
      <button class="btn btn-success" type="submit">Submit</button>
    </form>
</section>  
{% endblock dashboard_content %}

appointment/templates/appointment/make_appointment.html
{% extends 'dashboard.html'%}

{% block dashboard_content %}

<section id="make-appointment">
    <h3>Make an Appointment</h3>
    <form method="post"> {% csrf_token %}
      <div class="form-group">
        <label for="service">Select service</label>
        <select name="service" class="form-control">
          {% for service in services %}
          <option value="{{service.pk}}">{{service.service}}</option>
          {% endfor %}
        </select>
      </div>
      <div class="form-group">
        <label for="date">Date</label>
        <input name="date" type="date" class="form-control">
      </div>
      <button class="btn btn-success" type="submit">Submit</button>
    </form>
</section>  
{% endblock dashboard_content %}