appointment/urls.py
from django.urls import path
from appointment.views import (
    appointment_status_view,
    appointment_list_view,
    make_appointment_view,
    appointment_edit_view,
    appointment_change_status_view,
    appointment_delete_view,
)

app_name = 'appointment'

urlpatterns = [
    path('customer/status', appointment_status_view, name = "status"),
    path('staff/list', appointment_list_view, name = "list"),
    path('customer/make-appointment', make_appointment_view, name = "add"),
    path('customer/edit-appointment/<int:id>', appointment_edit_view, name = "edit"),
    path('staff/delete-appointment/<int:id>', appointment_delete_view, name = "delete"),
    path('change-status/<int:id>/<str:status>', appointment_change_status_view, name = "change-status"),
]

laboratoryapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home.views import home_screen_view
from account.views import (
    login_view,
    logout_view,
    registration_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name="home"),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('register/', registration_view, name="register"),
    path('appointment/', include('appointment.urls', 'appointment')),
    path('service/', include('services.urls', 'services')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

services/urls.py
from django.urls import path
from services.views import service_add_view, service_list_view, service_edit_view, service_delete_view

app_name = 'services'

urlpatterns = [
    path('list', service_list_view, name = 'list' ),
    path('add', service_add_view, name = 'add' ),
    path('edit/<int:id>', service_edit_view, name = "edit"),
    path('delete/<int:id>', service_delete_view, name = "delete"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Laboratory App</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Bootstrap scripts -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>    

    <!--Font awesome script-->
    <script src="https://kit.fontawesome.com/a6b8b45338.js" crossorigin="anonymous"></script>

    <!-- stylesheet -->
    <link rel="stylesheet" href="{% static 'css/style.css'%}">

</head>
<body>
    {% block content %}

    {% endblock content%}
</body>
</html>

templates/dashboard.html
{% extends 'base.html' %}

{% block content %}
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">President Lab</a>
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="{% url 'logout'%}">Logout</a>
        </li>
      </ul>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              {% if not request.user.is_staff %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'appointment:add' %}">
                  Make an Appointment
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'appointment:status' %}">
                  Appointment Status
                </a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'appointment:list' %}">
                  Appointment List
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'services:list' %}">
                  Services
                </a>
              </li>
              {% endif %}
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h1 class="h2">Welcome, {{user.first_name}}</h1>

          </div>
          {% block dashboard_content %}

          {% endblock dashboard_content %}
        </main>
      </div>
    </div>
{% endblock content%}