laboratoryapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home.views import home_screen_view
from account.views import (
    login_view,
    logout_view,
    registration_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name="home"),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('register/', registration_view, name="register"),
    path('appointment/', include('appointment.urls', 'appointment')),
    path('service/', include('services.urls', 'services')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

services/urls.py
from django.urls import path
from services.views import service_add_view, service_list_view, service_edit_view, service_delete_view

app_name = 'services'

urlpatterns = [
    path('list', service_list_view, name = 'list' ),
    path('add', service_add_view, name = 'add' ),
    path('edit/<int:id>', service_edit_view, name = "edit"),
    path('delete/<int:id>', service_delete_view, name = "delete"),
]

services/models.py
from django.db import models

# Create your models here.
class Services(models.Model):
    service_id = models.PositiveIntegerField(unique=True)
    service = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    price = models.IntegerField(default=0, verbose_name='price')

    def __str__(self):
        return self.service

services/forms.py
from django import forms
from services.models import Services

class AddService(forms.ModelForm):

    class Meta:
        model = Services 
        fields = ['service','description','price']

services/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseForbidden
from services.models import Services
from services.forms import AddService

# Create your views here.
def service_list_view(request):
    context = {}
    try :
        services = Services.objects.all()
        context['services'] = services
        return render(request, 'services/services.html', context)
    except Services.DoesNotExist:
        return render(request, 'services/services.html')

def service_add_view(request):
    context = {}

    user = request.user

    if request.POST:
        print('success 1')
        form = AddService(request.POST)

        if form.is_valid():
            print('success 2')
            obj = form.save(commit=False)
            service_id = get_new_service_id()
            obj.service_id = service_id
            obj.save()

            return redirect('services:list')

    else :
        form = AddService()

    return render(request, 'services/add_service.html', context)

def get_new_service_id():
    service = Services.objects.last()

    return service.service_id + 1

def service_edit_view(request, id):
    context = {}

    user = request.user

    if not user.is_authenticated:
        return HttpResponseForbidden()

    service = get_object_or_404(Services, service_id=id)

    if request.POST:
        print('success 1')
        form = AddService(request.POST, instance=service)

        if form.is_valid():
            print('success 2')
            form.save()

            return redirect('services:list')

    else :
        form = AddService()
    
    context['service'] = service

    return render(request, 'services/edit_service.html', context)

def service_delete_view(request, id):
    user = request.user
    if not user.is_authenticated:
        return HttpResponseForbidden()

    service = get_object_or_404(Services, service_id=id)

    service.delete()

    return redirect('service:list')

services/templates/services/add_service.html
{% extends 'dashboard.html'%}

{% block dashboard_content %}
<section id="add-service">
    <h3>Add a Service</h3>
    <form method="post"> {% csrf_token %}
      <div class="form-group">
        <label for="service">Title</label>
        <input type="text" name="service" class="form-control">
      </div>
      <div class="form-group">
        <label for="description">Description</label>
        <input type="text" name="description" class="form-control">
      </div>
      <div class="form-group">
        <label for="price">Price</label>
        <input type="number" name="price" class="form-control">
      </div>
      <button class="btn btn-success" type="submit">Submit</button>
    </form>
</section>  
{% endblock dashboard_content %}

services/templates/services/edit_service.html
{% extends 'dashboard.html'%}

{% block dashboard_content %}
<section id="edit-service">
    <h3>Edit Service</h3>
    <form method="post"> {% csrf_token %}
      <div class="form-group">
        <label for="service">Title</label>
        <input type="text" value="{{service.service}}" name="service" class="form-control">
      </div>
      <div class="form-group">
        <label for="description">Description</label>
        <input type="text"  value="{{service.description}}" name="description" class="form-control">
      </div>
      <div class="form-group">
        <label for="price">Price</label>
        <input type="number"  value="{{service.price}}" name="price" class="form-control">
      </div>
      <button class="btn btn-success" type="submit">Submit</button>
    </form>
</section>  
{% endblock dashboard_content %}

services/templates/services/services.html
{% extends 'dashboard.html'%}

{% block dashboard_content %}
<section id="service-list">
  <h3>Services</h3>
  <table class="table">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Service</th>
          <th scope="col">Description</th>
          <th scope="col">Price</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for service in services %}
        <tr>
          <td scope="row">{{service.service_id}}</td>
          <td scope="row">{{service.service}}</td>
          <td scope="row">{{service.description}}</td>
          <td scope="row">{{service.price}}</td>
          <td scope="row">
            <a href="{% url 'services:edit' service.service_id %}" class="btn btn-warning btn-sm my-1">Edit</a>
            <a href="{% url 'services:delete' service.service_id%}" class="btn btn-danger btn-sm my-1">Remove</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <a class="btn btn-success mb-5" href="{% url 'services:add' %}">Add Service</a>
  </section>  
  {% endblock dashboard_content %}